title: LEE YatMing Liam
logo: /assets/CV.jpg
description: Nice to meet you! Here is my CV, I’m passionate about data analysis, machine learning, and turning raw information into actionable insights. I know about Regression models, Clustering, Classifiers, and other machine learning methods like sentiment analysis and emotion analysis, If you want to see my projects, just feel free to my Projects Page!
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
footer:
  show: false
custom_css: |
  footer {
      display: none; /* Hides the entire footer */
  }
